# Generated by Django 5.2.14 on 2026-05-13 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers_remove_user_first_name_and_more'),
    ]

    operations = [
    ]
