"""
Django settings for teacher_django project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Load environment variables from .env file if it exists
env_file = Path(__file__).resolve().parent.parent / '.env'
if env_file.exists():
    with open(env_file, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            # Skip empty lines and comments
            if not line or line.startswith('#'):
                continue
            # Handle lines with =
            if '=' in line:
                key, value = line.split('=', 1)
                os.environ[key.strip()] = value.strip()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-h128yeca)nbs6o4qpc(42itzgmi)$gj89(2+@+esv!v+6njpe7')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Custom apps
    'core',
    'auth_app',
    'profile_app',
    'curriculum_app',
    'chat_app',
    # Agent system: 个性化学习与多智能体骨架
    'agent_system',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise：由 Django 进程直接托管静态文件（DEBUG=False 时 runserver 不再托管），
    # 部署到容器/gunicorn 时无需额外 nginx 即可提供 /static/。必须紧跟 SecurityMiddleware。
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'teacher_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'teacher_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# ---------------------------------------------------------------------------
# 数据库
# 默认 SQLite（本地开发）。要切到远程 MySQL：在 .env 里设 DB_ENGINE=mysql，
# 并配好 DB_NAME / DB_USER / DB_PASSWORD / DB_HOST / DB_PORT 即可，无需改代码。
# MySQL 一律用 utf8mb4，保证中文与 emoji（大纲/思维导图里有）不丢字。
# ---------------------------------------------------------------------------
if os.getenv('DB_ENGINE', 'sqlite').lower() in ('mysql', 'django.db.backends.mysql'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME', 'tri'),
            'USER': os.getenv('DB_USER', 'root'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('DB_PORT', '3306'),
            # 复用连接，减少每请求重连开销（0 表示每次请求都新建/关闭）
            'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '60')),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                # 禁用 TLS：该服务器的 SSL 握手会返回畸形数据（ASN1 报错），
                # 内网走明文即可。要启用 TLS 时删掉此行并配好证书。
                'ssl_disabled': True,
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'data' / 'users.db',  # 数据库文件现在在 teacher_django/data/ 目录下
            # busy_timeout：并发生成时多个线程会同时写进度，SQLite 写锁下让后来者最多等 20s 而非
            # 立刻抛 "database is locked"。支撑资源级/分页级并行。
            'OPTIONS': {'timeout': 20},
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise 静态存储：压缩但不做 manifest 哈希（manifest 会在模板引用了不存在的静态文件时
# 直接报错，用非 manifest 版更稳）。collectstatic 会把文件收集到 STATIC_ROOT。
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Custom User Model
AUTH_USER_MODEL = 'core.User'

# Login URL
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# iFlytek 星火（讯飞）相关设置
# 支持两套环境变量命名：XINGHUO_*（首选）和 XUNFEI_*（兼容历史 .env）
XINGHUO_API_URL = os.getenv('XINGHUO_API_URL') or os.getenv('XUNFEI_API_URL', '')
XINGHUO_API_KEY = os.getenv('XINGHUO_API_KEY') or os.getenv('XUNFEI_API_KEY', '')
XINGHUO_DEFAULT_MODEL = os.getenv('XINGHUO_DEFAULT_MODEL') or os.getenv('XUNFEI_MODEL', '')
XINGHUO_TIMEOUT = int(os.getenv('XINGHUO_TIMEOUT') or os.getenv('XUNFEI_TIMEOUT', '30'))
# 简单的敏感词/违禁词列表，可在 .env 中用逗号分隔覆盖 XINGHUO_SAFETY_BANLIST
XINGHUO_SAFETY_BANLIST = [w for w in (os.getenv('XINGHUO_SAFETY_BANLIST') or os.getenv('XUNFEI_SAFETY_BANLIST', '')).split(',') if w]

# ── 生成快速开关（本地/慢模型测试用，提交前请关掉）──────────────────────────
# GENERATION_RESOURCE_TYPES：只生成哪些资源。留空=按默认全生成；填 "ppt" 只生成 PPT；
#   多选用逗号，如 "ppt,quiz"。可选值：doc(讲义)/ppt/quiz(题库)/code(代码)/mindmap(导图)/reading(阅读)
GENERATION_RESOURCE_TYPES = os.getenv('GENERATION_RESOURCE_TYPES', '')
# GENERATION_FAST_MODE=true：跳过最烧时间的反思重生成 / PPT 一致性重写 / 讲义防幻觉审校
GENERATION_FAST_MODE = os.getenv('GENERATION_FAST_MODE', 'False').lower() == 'true'

# ── 生成并发（本地 GPU 上大幅提速；星火免费档并发低要调回小值）─────────────────────
# XINGHUO_MAX_CONCURRENCY：PPT 分页/修订的并行线程数（默认 2，星火免费档并发~2）。
#   GPU 自建 Ollama 可调到 4~6，但需在实例上同步把 OLLAMA_NUM_PARALLEL 调到同样大小，否则 Ollama 仍串行。
XINGHUO_MAX_CONCURRENCY = int(os.getenv('XINGHUO_MAX_CONCURRENCY', '2'))
# GENERATION_RESOURCE_CONCURRENCY：doc/ppt/quiz/code/mindmap/reading 这些相互独立的资源的并行数。
#   默认 1=串行（最稳，兼容星火免费档）；GPU 上可设 3 让它们同时生成。
GENERATION_RESOURCE_CONCURRENCY = int(os.getenv('GENERATION_RESOURCE_CONCURRENCY', '1'))

# Celery / broker settings
# 本地开发默认使用 127.0.0.1 的 Redis；容器环境请显式覆盖为对应主机名
# （docker-compose 里 web/worker 两个服务都设了 CELERY_BROKER_URL=redis://redis:6379/0）。
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/1')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# PPTX 导出默认走后台线程，不默认经 Celery（原有设计——导出偏一次性、文件产出型任务，
# 队列化收益不大）。需要时在 .env / .env.docker 里显式设 USE_CELERY_FOR_PPTX_EXPORT=true 打开。
USE_CELERY_FOR_PPTX_EXPORT = os.getenv('USE_CELERY_FOR_PPTX_EXPORT', 'False').lower() == 'true'