# Generated by Django 5.2.14 on 2026-05-13 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(default='default', max_length=100)),
                ('asked_dimensions', models.TextField()),
                ('answered_dimensions', models.TextField()),
                ('skipped_dimensions', models.TextField()),
                ('conversation_history', models.TextField()),
                ('current_round', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_conversation_sessions',
                'indexes': [models.Index(fields=['user', 'course_id'], name='profile_con_user_id_8871d6_idx'), models.Index(fields=['status'], name='profile_con_status_463f8f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfileEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('event_payload', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_events',
                'indexes': [models.Index(fields=['user'], name='profile_eve_user_id_5d60e9_idx'), models.Index(fields=['event_type'], name='profile_eve_event_t_526faa_idx'), models.Index(fields=['created_at'], name='profile_eve_created_134854_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(default='default', max_length=100)),
                ('profile_data', models.TextField()),
                ('confidence_scores', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_profiles',
                'indexes': [models.Index(fields=['user', 'course_id'], name='student_pro_user_id_9af865_idx'), models.Index(fields=['last_updated'], name='student_pro_last_up_430b40_idx')],
                'unique_together': {('user', 'course_id')},
            },
        ),
    ]
