# Generated by Django 4.2.30 on 2026-06-13 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(default='default', max_length=100)),
                ('radar_labels', models.TextField()),
                ('radar_values', models.TextField()),
                ('knowledge_snapshot', models.TextField(blank=True, default='{}')),
                ('profile_hash', models.CharField(max_length=64)),
                ('ai_narrative', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_snapshots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'course_id', '-created_at'], name='profile_snap_user_crs_idx'), models.Index(fields=['profile_hash'], name='profile_snap_hash_idx')],
            },
        ),
    ]
