# Generated by Django 5.2.14 on 2026-05-13 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOutline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('estimated_hours', models.FloatField(default=0)),
                ('outline_data', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_outlines',
            },
        ),
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_id', models.CharField(max_length=100)),
                ('concept_name', models.CharField(max_length=200)),
                ('animation_code', models.TextField()),
                ('animation_type', models.CharField(choices=[('css', 'CSS'), ('canvas', 'Canvas'), ('svg', 'SVG')], default='css', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum_app.courseoutline')),
            ],
            options={
                'db_table': 'animations',
            },
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('completed_slides', models.IntegerField(default=0)),
                ('total_slides', models.IntegerField(default=0)),
                ('quiz_score', models.FloatField(default=0)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum_app.courseoutline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learning_progress',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_id', models.CharField(max_length=100)),
                ('slide_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum_app.courseoutline')),
            ],
            options={
                'db_table': 'slides',
            },
        ),
        migrations.AddIndex(
            model_name='courseoutline',
            index=models.Index(fields=['user'], name='course_outl_user_id_21b181_idx'),
        ),
        migrations.AddIndex(
            model_name='courseoutline',
            index=models.Index(fields=['status'], name='course_outl_status_626cac_idx'),
        ),
        migrations.AddIndex(
            model_name='animation',
            index=models.Index(fields=['course_outline'], name='animations_course__3daea3_idx'),
        ),
        migrations.AddIndex(
            model_name='animation',
            index=models.Index(fields=['chapter_id'], name='animations_chapter_e11815_idx'),
        ),
        migrations.AddIndex(
            model_name='learningprogress',
            index=models.Index(fields=['user'], name='learning_pr_user_id_6d6977_idx'),
        ),
        migrations.AddIndex(
            model_name='learningprogress',
            index=models.Index(fields=['course_outline'], name='learning_pr_course__3e9c83_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='learningprogress',
            unique_together={('user', 'course_outline', 'chapter_id')},
        ),
        migrations.AddIndex(
            model_name='slide',
            index=models.Index(fields=['course_outline'], name='slides_course__b025b7_idx'),
        ),
        migrations.AddIndex(
            model_name='slide',
            index=models.Index(fields=['chapter_id'], name='slides_chapter_73919e_idx'),
        ),
    ]
