# Generated by Django on 2026-05-16
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoutline',
            name='exported_pptx',
            field=models.CharField(max_length=512, null=True, blank=True),
        ),
    ]
