# Generated by Django 4.2.30 on 2026-05-16 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum_app', '0002_add_exported_pptx'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('plan_data', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learning_plans',
                'indexes': [models.Index(fields=['user'], name='learning_pl_user_id_5d0044_idx'), models.Index(fields=['status'], name='learning_pl_status_7e1e4b_idx')],
            },
        ),
    ]
