# Generated by Django 4.2.30 on 2026-05-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_app', '0003_learningplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoutline',
            name='export_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseoutline',
            name='export_status',
            field=models.CharField(default='idle', max_length=20),
        ),
        migrations.AddIndex(
            model_name='courseoutline',
            index=models.Index(fields=['export_status'], name='course_outl_export__8879df_idx'),
        ),
    ]
