# Generated by Django 4.2.30 on 2026-05-16 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum_app', '0004_courseoutline_export_progress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlineExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(blank=True, max_length=512, null=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('filesize', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course_outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='curriculum_app.courseoutline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'outline_exports',
                'indexes': [models.Index(fields=['course_outline'], name='outline_exp_course__b77d16_idx'), models.Index(fields=['status'], name='outline_exp_status_857d8b_idx')],
            },
        ),
    ]
