# Generated by Django 4.2.30 on 2026-05-27 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum_app', '0005_outlineexport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('source_type', models.CharField(choices=[('uploaded', 'Uploaded'), ('generated', 'Generated')], default='uploaded', max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('login', 'Login Users'), ('public', 'Public')], default='login', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='course_covers/')),
                ('tags', models.CharField(blank=True, default='', max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('material_type', models.CharField(choices=[('pdf', 'PDF'), ('ppt', 'PPT/PPTX'), ('doc', 'DOC/DOCX'), ('video', 'Video'), ('image', 'Image'), ('archive', 'Archive'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='course_materials/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, default='')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('file_size', models.BigIntegerField(default=0)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='curriculum_app.course')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_course_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_materials',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('source_page', models.CharField(blank=True, default='', max_length=50)),
                ('heading', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField()),
                ('keyword_summary', models.CharField(blank=True, default='', max_length=255)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='curriculum_app.coursematerial')),
            ],
            options={
                'db_table': 'material_chunks',
                'ordering': ['material', 'chunk_index'],
                'indexes': [models.Index(fields=['material'], name='material_ch_materia_8b4ee1_idx'), models.Index(fields=['source_page'], name='material_ch_source__e04336_idx')],
                'unique_together': {('material', 'chunk_index')},
            },
        ),
        migrations.AddIndex(
            model_name='coursematerial',
            index=models.Index(fields=['course'], name='course_mate_course__aa9569_idx'),
        ),
        migrations.AddIndex(
            model_name='coursematerial',
            index=models.Index(fields=['material_type'], name='course_mate_materia_839bfd_idx'),
        ),
        migrations.AddIndex(
            model_name='coursematerial',
            index=models.Index(fields=['processing_status'], name='course_mate_process_d43683_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['owner'], name='courses_owner_i_aed92a_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='courses_status_67f368_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['visibility'], name='courses_visibil_88ced3_idx'),
        ),
    ]
