# Generated by Django 4.2.30 on 2026-05-28 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent_system', '0002_conversation_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum_app', '0006_course_coursematerial_materialchunk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_snapshot', models.JSONField(blank=True, default=dict)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('question_fingerprints', models.JSONField(blank=True, default=list)),
                ('knowledge_tags', models.JSONField(blank=True, default=list)),
                ('recommended_review_pages', models.JSONField(blank=True, default=list)),
                ('difficulty_stage', models.CharField(choices=[('standard', 'Standard'), ('reinforce', 'Reinforce'), ('progressive', 'Progressive'), ('challenge', 'Challenge')], default='standard', max_length=20)),
                ('focus_question_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('score', models.FloatField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_quiz_attempts', to='curriculum_app.course')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='curriculum_app.coursematerial')),
                ('quiz_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_quiz_attempts', to='agent_system.learningresource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'material_quiz_attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'material'], name='material_qu_user_id_7fe7e3_idx'), models.Index(fields=['course', 'material'], name='material_qu_course__0556ad_idx'), models.Index(fields=['created_at'], name='material_qu_created_836eb4_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaterialQuestionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_fingerprint', models.CharField(max_length=64)),
                ('question_text', models.TextField(blank=True, default='')),
                ('canonical_answer', models.TextField(blank=True, default='')),
                ('explanation', models.TextField(blank=True, default='')),
                ('knowledge_tag', models.CharField(blank=True, default='', max_length=255)),
                ('source_page', models.CharField(blank=True, default='', max_length=50)),
                ('source_heading', models.CharField(blank=True, default='', max_length=255)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('seen_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('consecutive_wrong_count', models.PositiveIntegerField(default=0)),
                ('similar_generation_count', models.PositiveIntegerField(default=0)),
                ('last_result_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_question_stats', to='curriculum_app.course')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_stats', to='curriculum_app.coursematerial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_question_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'material_question_stats',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', 'material'], name='material_qu_user_id_71301f_idx'), models.Index(fields=['knowledge_tag'], name='material_qu_knowled_32a605_idx'), models.Index(fields=['wrong_count'], name='material_qu_wrong_c_6429dd_idx'), models.Index(fields=['consecutive_wrong_count'], name='material_qu_consecu_7bfcc1_idx')],
                'unique_together': {('user', 'material', 'question_fingerprint')},
            },
        ),
    ]
