# Generated by Django 4.2.30 on 2026-06-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_app', '0009_materialquizadaptivepolicy'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='materialquizadaptivepolicy',
            new_name='material_qu_user_id_adbb89_idx',
            old_name='material_qu_user_id_20566d_idx',
        ),
        migrations.RenameIndex(
            model_name='materialquizadaptivepolicy',
            new_name='material_qu_course__695223_idx',
            old_name='material_qu_course__3e0af0_idx',
        ),
        migrations.RenameIndex(
            model_name='materialquizadaptivepolicy',
            new_name='material_qu_updated_303e7e_idx',
            old_name='material_qu_updated_4795f8_idx',
        ),
    ]
