# Generated by Django 4.2.30 on 2026-06-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_app', '0010_rename_material_qu_user_id_20566d_idx_material_qu_user_id_adbb89_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialquestionstat',
            name='elo_rating',
            field=models.FloatField(default=1200.0),
        ),
        migrations.AddField(
            model_name='materialquizadaptivepolicy',
            name='ability_rating',
            field=models.FloatField(default=1200.0),
        ),
    ]
