# Generated by Django 4.2.30 on 2026-07-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_app', '0011_materialquestionstat_elo_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialchunk',
            name='keyword_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
