# Generated by GitHub Copilot

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent_system', '0003_alter_learningresource_resource_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('source_app', models.CharField(blank=True, default='', max_length=80)),
                ('course_id', models.IntegerField(blank=True, null=True)),
                ('material_id', models.IntegerField(blank=True, null=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('profile_delta', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_profile_events',
            },
        ),
        migrations.AddIndex(
            model_name='profileevent',
            index=models.Index(fields=['user', 'event_type', 'created_at'], name='agent_profi_user_id_c5bd27_idx'),
        ),
        migrations.AddIndex(
            model_name='profileevent',
            index=models.Index(fields=['processed_at'], name='agent_profi_process_66f68f_idx'),
        ),
    ]
