# Generated by Django 4.2.30 on 2026-06-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent_system', '0004_profileevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='messages_convers_3ebb41_idx',
            old_name='messages_convers_1db366_idx',
        ),
    ]
