# Generated by Django 4.2.30 on 2026-06-08 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent_system', '0005_rename_messages_convers_1db366_idx_messages_convers_3ebb41_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='cold_start_progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='inference_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_cold_start',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_inference_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='recent_inferences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ReasoningChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('conversation_id', models.IntegerField(blank=True, null=True)),
                ('reasoning_steps', models.JSONField(default=list)),
                ('profile_delta', models.JSONField(default=dict)),
                ('confidence', models.FloatField(default=0.0)),
                ('validation_result', models.JSONField(default=dict)),
                ('inference_time', models.DateTimeField(auto_now_add=True)),
                ('profile_version', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasoning_chains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inference_time'],
                'indexes': [models.Index(fields=['user', 'inference_time'], name='agent_syste_user_id_efee0b_idx'), models.Index(fields=['conversation_id'], name='agent_syste_convers_35cb0f_idx')],
            },
        ),
    ]
