# Generated by Django 4.2.30 on 2026-06-08 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent_system', '0006_studentprofile_cold_start_progress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipartMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality_type', models.CharField(choices=[('text', '文本'), ('image', '图片'), ('audio', '音频'), ('file', '文件')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_parts', to='agent_system.message')),
            ],
            options={
                'db_table': 'agent_multipart_messages',
            },
        ),
        migrations.CreateModel(
            name='EventEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_vector', models.JSONField(default=list)),
                ('embedding_model', models.CharField(default='sha256_hash', max_length=100)),
                ('dimension', models.IntegerField(default=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_record', to='agent_system.profileevent')),
            ],
            options={
                'db_table': 'agent_event_embeddings',
                'indexes': [models.Index(fields=['embedding_model'], name='agent_event_embeddi_e487f1_idx')],
            },
        ),
    ]
