# Generated by Django 4.2.30 on 2026-06-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_system', '0007_add_event_embedding_multipart'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='peer_memory_stream',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
