# Generated by Django 4.2.30 on 2026-06-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_system', '0008_studentprofile_peer_memory_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='knowledge_timestamps',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
